# netlify.toml

[build]
  # This is the directory where your main website files are located.
  # If your index.html is directly in the root, use "."
  # If it's in a subfolder like 'thesendoff', use "thesendoff".
  publish = "thesendoff-frontend" # Adjust this if your main website files are in a different directory

  # No build command needed for a static HTML/CSS/JS site.
  command = ""

[functions]
  # This tells Netlify where to find your serverless functions.
  # It should point to the folder containing your function files (e.g., 'generate-ai-content.js').
  directory = "netlify/functions"
